[project]
name = "pixi"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
codespell = ">=2.2.6,<2.3"
cmake = "<3.27"
compilers = ">=1.7.0,<1.8"
cmake-format = ">=0.6.13,<0.7"
npx = ">=0.1.1,<0.2"
doxygen = ">=1.10.0,<1.11"
ninja = ">=1.11.1,<1.12"
ghostscript = ">=10.2.1,<10.3"
texlive-core = ">=20230313,<20230314"
pip = ">=24.0,<25"
cppcheck = ">=2.13.1,<2.14"
nvim = ">=0.9.5,<0.10"
prettier = ">=3.2.5,<3.3"
nodejs = ">=20.9.0,<20.10"
cuda = ">=12.3.2,<12.4"
cffi = ">=1.16.0,<1.17"
ocl-icd-system = ">=1.0.0,<1.1"
ocl-icd = ">=2.3.2,<2.4"
libva-utils = ">=2.20.1,<2.21"
libva = ">=2.20.0,<2.21"
procps-ng = ">=4.0.4,<4.1"
intel-opencl-rt = ">=2024.0.0,<2024.1"
spirv-tools = ">=2023.2,<2024"
spirv-headers = ">=1.3.261.1,<1.3.262"
libllvmspirv = ">=16.0.0,<16.1"

[tasks]
clone-llvm-sycl = "git clone https://github.com/intel/llvm -b sycl-web/sycl-latest-good --depth=1 llvm-source"
configure-llvm-build = { cmd = "sh configure.sh", depends_on = ["clone-llvm-sycl"] }
build-llvm = { cmd = "sh build_sycl.sh", depends_on = ["configure-llvm-build"] }
install-llvm = { cmd = "sh install_sycl.sh", depends_on = ["build-llvm"] }
